---
galaxy_info:
  author: Max Whittingham
  description: This role is designed to upgrade an OpenShift Master running at least 3.2.1.9
  company: Red Hat
   - Apache
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - 7
  categories:
  - cloud
dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
