---

- name: Get the routing subdomain from the master
  yedit:
    state: list
    src: /etc/origin/master/master-config.yaml
    key: routingConfig.subdomain
  register: subdomain
  run_once: true

# task to insall rpm
- name: install the latest version of openshift-scripts-devpreview
  yum:
    name: openshift-scripts-devpreview
    state: present

- name: Create customrouter configmap
  oc_configmap:
    state: present
    name: customrouter
    namespace: default
    from_file:
      template: /etc/openshift-online/templates/haproxy-config.template
  register: configmap_out
  run_once: true

# The oc_volume command does not currently support a configmap source. Falling back to command module.
- name: Add a volume to the router
  command: >
    oc set volume dc/router --add --overwrite --name=config-volume --mount-path=/var/lib/haproxy/conf/custom --configmap-name=customrouter
  run_once: true

- name: Add our env vars to new customrouter
  oc_env:
    kind: dc
    name: router
    env_vars:
      ROUTER_OVERRIDE_HOSTNAME: "false"
      ROUTER_CLOUD_DOMAIN: "{{ subdomain.result }}"
      TEMPLATE_FILE: /var/lib/haproxy/conf/custom/haproxy-config.template
      EXTENDED_VALIDATION: "true"
  run_once: true
