#!/usr/bin/ansible-playbook
---
- name: "Playbook to un-schedule and drain drain compute nodes before remediating runc on them"
  hosts: localhost
  user: root

  pre_tasks:
  - fail:
      msg: "This playbook requires {{item}} to be set."
    when: item is not defined or item == ''
    with_items:
    - cli_master
    - cli_node
    - cli_ssh_name

  tasks:
    - name: "debug"
      debug:
        msg: "{{ item }}"
      with_items:
      -  "{{ cli_master }}"
      -  "{{ cli_node }}"
      -  "{{ cli_ssh_name }}"


      # Test connectivity
    - name: "Test ssh connection to the node from a bastion"
      delegate_to: "root@{{ item }}"
      shell: "uptime"
      with_items:
      -  "{{ cli_master }}"
      -  "{{ cli_ssh_name }}"


      # Begin master operations
    - name: "Test oc get node from the primary master"
      shell: "oc get node {{ cli_node }}"
      delegate_to: "root@{{ cli_master }}"

    - name: "Try to unschedule the node from the primary master"
      shell: "oc adm manage-node {{ cli_node }} --schedulable=false"
      delegate_to: "root@{{ cli_master }}"

    - name: "Try to drain the node from the primary master"
      shell: "oc adm drain {{ cli_node }} --force --ignore-daemonsets --delete-local-data"
      delegate_to: "root@{{ cli_master }}"
      ignore_errors: true


    # Begin node operations
    - name: "Disable docker before rebooting"
      shell: "systemctl disable docker var-lib-docker.mount"
      delegate_to: "root@{{ cli_ssh_name }}"

    - name: "Reboot node to disable docker"
      shell: "sleep 2 && shutdown -r now"
      async: 5
      poll: 0
      delegate_to: "root@{{ cli_ssh_name }}"

    - name: "Pause for 1 minute to allow the node to finish rebooting."
      pause:
        minutes: 1

    - name: "Wait for the node to come back up"
      shell: "uptime"
      retry: 5
      delay: 60
      delegate_to: "root@{{ cli_ssh_name }}"
      ignore_errors: true

    - name: "Make sure docker is stopped and unmounted"
      shell: "systemctl stop docker var-lib-docker.mount"
      delegate_to: "root@{{ cli_ssh_name }}"


    # Begin bastion operations
    - name: "Start docker reinitialization playbook from a bastion"
      shell: "ansible-playbook ops-docker-storage-reinitialize.yml -e cli_name={{ cli_ssh_name }} -e cli_confirm_run=yes"
      delegate_to: localhost


    # Continue node operations
    - name: "Try to apply docker update first, then the rest of the pending updates, reenable docker"
      shell: "{{ item }}"
      with_items:
      - "yum -y update --advisory=RHSA-2019:0304"
      - "yum -y update --security"
      - "systemctl enable docker var-lib-docker.mount"
      delegate_to: "root@{{ cli_ssh_name }}"
      ignore_errors: true

    - name: "Reboot node to re enable docker"
      shell: "sleep 2 && shutdown -r now"
      async: 5
      poll: 0
      delegate_to: "root@{{ cli_ssh_name }}"

    - name: "Pause for 1 minute to allow the node to finish rebooting."
      pause:
        minutes: 1

    - name: "Wait for the node to come back up again"
      shell: "uptime"
      retry: 5
      delay: 40
      delegate_to: "root@{{ cli_ssh_name }}"
      ignore_errors: true

    - name: "Check if host is still vulnerable"
      shell: "bash /root/runc_check.sh"
      delegate_to: "root@{{ cli_ssh_name }}"
      ignore_errors: true


    # Finish master operations
    - name: "Try to schedule the node from the primary master"
      shell: "oc adm manage-node {{ cli_node }} --schedulable=true"
      delegate_to: "root@{{ cli_master }}"

    - name: "Check if node is back in Ready state from the primary master"
      shell: "oc get node {{ cli_node }}"
      delegate_to: "root@{{ cli_master }}"
