---
- hosts: localhost
  gather_facts: no
  vars_files:
  - /root/default_vars.yml

  vars:
    sigpull_cron:
    - name: cron_pull_signatures
      minute: "15"
      hour: "*/12"
      job: "/usr/local/bin/pull_clam_signatures &>/dev/null"

  tasks:
  - name: Setup Cron
    cron:
      name: "{{ item.name }}"
      job: "{{ item.job }}"
      minute: "{{ item.minute | default('*', True) }}"
      hour: "{{ item.hour | default('*', True) }}"
      day: "{{ item.day | default('*', True) }}"
      month: "{{ item.month | default('*', True) }}"
      weekday: "{{ item.weekday | default('*', True) }}"
    with_items:
    - "{{ sigpull_cron }}"
