---
- name: Install needed RPMs
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - openshift-tools-scripts-inventory-clients
  - openshift-tools-scripts-monitoring-zagg-client

- file:
    state: directory
    dest: /etc/ansible/inventory
    owner: root
    group: libra_ops
    mode: 0750

- file:
    state: link
    src: /usr/share/ansible/inventory/multi_inventory.py
    dest: /etc/ansible/inventory/multi_inventory.py
    owner: root
    group: libra_ops

# This cron uses the above location to call its job
- name: Cron to keep cache fresh
  cron:
    name: 'multi_inventory'
    minute: '*/10'
    job: '/usr/bin/ops-runner -n cmirc.multi_inventory.refresh -t 60 /usr/share/ansible/inventory/multi_inventory.py --refresh-cache &> /dev/null'
  when: oo_cron_refresh_cache is defined and oo_cron_refresh_cache

- name: Set cache location
  file:
    state: directory
    dest: "{{ oo_inventory_cache_location | dirname }}"
    owner: root
    group: libra_ops
    recurse: yes
    mode: '2770'
  when: oo_inventory_cache_location is defined
