---
- name: Ensure docker is installed
  package:
    name: docker
    state: present

- name: Copy the docker-storage-setup config file
  template:
    src: "{{ item }}"
    dest: /etc/sysconfig/docker-storage-setup
    owner: root
    group: root
    mode: 0664
  with_first_found:
    - "{{ dss_docker_storage_driver }}_dss.j2"
    - devicemapper_dss.j2

- name: Ensure docker is started
  service:
    name: docker
    state: started
    enabled: true

- name: docker info
  command: docker info
  register: dockerinfo

- debug:
    msg: "{{ dockerinfo }}"
