---
# tasks file for openshift_master_upgrade
#- name: Remove Masters from elbs
# This is probably best as it's own role since elbs are AWS specific

- name: Find the master's ip address #unfinished

- name: Stop OpenShift API
  service: 
    name: atomic-openshift-master-api
    state: stopped

- name: Stop OpenShift Controller
  service: 
    name: atomic-openshift-master-controllers
    state: stopped

- name: Remove the current master from the kubnernetes endpoints #unfinished
  lineinfile: 

- name: Yum update docker
  yum:
    name: docker-1.9.1-40.el7,docker-selinux-1.9.1-40.el7
    state: present

- name: Ensure no further updates to Docker are allowed 
  lineinfile:
    dest: /etc/yum.repos.d/oso-rhui-rhel-server-extras.repo
    backup: yes
    insertafter: 'enabled=1'
    line: 'exclude=docker-*'
    state: present
   
- name: Upgrade everything else
  yum:
    name: *
    state: latest
#   exclude: docker #Requires Ansible 2.0 

- name: Reboot #unfinished
