---
# tasks file for openshift_master_upgrade
#- name: Remove Masters from elbs
# This is probably best as it's own role since elbs are AWS specific

- name: Stop OpenShift API
  service: 
    name: atomic-openshift-master-api
    state: stopped

- name: Stop OpenShift Controller
  service: 
    name: atomic-openshift-master-controllers
    state: stopped

- name: Ensure that the Master IP address is out of the Kubernetes endpoint #This will only remove the IP from the enpoint in 3.2.1.9 and later
  pause:
    seconds: 5

- name: Yum update docker
  yum:
    name: docker-1.9.1-40.el7,docker-selinux-1.9.1-40.el7
    state: present

- name: Upgrade everything else
  yum:
    name: '*'
    state: latest
    exclude: docker #Requires Ansible 2.0 

- name: Reboot 
  shell: reboot
